// Fictional examples for exploring the UI, one near each supported
// university. Coordinates are approximate and must not be treated as
// available properties or exact building locations.
export const mockListings = [
  {
    id: "sample-chula-studio",
    is_mock: true,
    university_id: "e956675d-085e-4716-940c-02424174c782",
    title: "Siam Square Studio",
    property_type: "room",
    monthly_rent: 7900,
    address: "Near Chulalongkorn University, Pathumwan, Bangkok",
    latitude: 13.7395,
    longitude: 100.5285,
    description: "Example furnished studio with a double bed, study desk, wardrobe, air conditioning and a private bathroom, an easy walk to campus. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/muang-ake-studio.jpg",
    status: "published",
  },
  {
    id: "sample-thammasat-condo",
    is_mock: true,
    university_id: "1c731019-d77a-4533-aea4-1c63c7f951d0",
    title: "Rangsit Campus Lane Condo",
    property_type: "condo",
    monthly_rent: 8200,
    address: "Near Thammasat University Rangsit Campus, Khlong Luang, Pathum Thani",
    latitude: 14.0689,
    longitude: 100.6102,
    description: "Example one-bedroom condo with a separate sleeping area, compact kitchen, balcony and living space. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/muang-ake-condo.jpg",
    status: "published",
  },
  {
    id: "sample-kasetsart-room",
    is_mock: true,
    university_id: "91e61342-49ef-4b9c-b23e-2694744aee80",
    title: "Ladyao Study Room",
    property_type: "room",
    monthly_rent: 4500,
    address: "Near Kasetsart University, Chatuchak, Bangkok",
    latitude: 13.8501,
    longitude: 100.5735,
    description: "Example budget student room with a single bed, desk, wardrobe and air conditioning. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/lak-hok-room.jpg",
    status: "published",
  },
  {
    id: "sample-mahidol-studio",
    is_mock: true,
    university_id: "01c42f18-6683-475a-b970-f963f6469ac8",
    title: "Salaya Riverside Studio",
    property_type: "apartment",
    monthly_rent: 6500,
    address: "Near Mahidol University Salaya Campus, Nakhon Pathom",
    latitude: 13.7938,
    longitude: 100.3199,
    description: "Example furnished studio with a kitchenette, double bed, balcony and work area near the Salaya campus. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/station-studio.jpg",
    status: "published",
  },
  {
    id: "sample-chiangmai-apartment",
    is_mock: true,
    university_id: "044680d9-498a-4f58-b937-f74459d39c7d",
    title: "Nimman Two-Bedroom Share",
    property_type: "apartment",
    monthly_rent: 9500,
    address: "Near Chiang Mai University, Nimman area, Chiang Mai",
    latitude: 18.7989,
    longitude: 98.9575,
    description: "Example two-bedroom apartment suitable for sharing, with a living room, dining area, balcony and kitchenette. The rent shown is for the whole apartment. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/shared-apartment.jpg",
    status: "published",
  },
  {
    id: "sample-rangsit-studio",
    is_mock: true,
    university_id: "10ffe474-15b6-470f-9073-9f5a71c122b1",
    title: "Muang Ake Garden Studio",
    property_type: "room",
    monthly_rent: 5900,
    address: "Muang Ake, Lak Hok, Pathum Thani",
    latitude: 13.9644,
    longitude: 100.5818,
    description: "Example furnished studio with a double bed, study desk, wardrobe, air conditioning and a private bathroom. The location shown is approximate. This is sample data, not an available rental.",
    image_path: "/images/listings/muang-ake-studio.jpg",
    status: "published",
  },
];

export function getMockListing(id) {
  return mockListings.find((listing) => listing.id === id) ?? null;
}
